#!/usr/bin/env bash
# Local markdown ticket queue. No dependencies beyond coreutils.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TDIR="$ROOT/docs/tickets"
OPEN="$TDIR/open"
DONE="$TDIR/done"

usage() {
  cat <<'USAGE'
usage:
  ticket.sh new "Title"            create the next ticket
  ticket.sh status <id> <state>    needs-triage|needs-info|ready|blocked|in-progress|done|wontfix
  ticket.sh close <id>             mark done and move to done/
  ticket.sh index                  rebuild INDEX.md
  ticket.sh show <id>              print a ticket
  ticket.sh list [state]           list open tickets, optionally filtered
USAGE
}

find_ticket() {
  local id="$1"
  local f
  f=$(find "$OPEN" "$DONE" -name "${id}-*.md" 2>/dev/null | head -1)
  [ -z "$f" ] && { echo "No ticket $id" >&2; exit 1; }
  echo "$f"
}

field() { grep -m1 "^$2:" "$1" | sed "s/^$2:[[:space:]]*//"; }

next_id() {
  local max=0 n
  for f in "$OPEN"/*.md "$DONE"/*.md; do
    [ -e "$f" ] || continue
    n=$(basename "$f" | cut -d- -f1)
    case "$n" in ''|*[!0-9]*) continue;; esac
    n=$((10#$n))
    [ "$n" -gt "$max" ] && max=$n
  done
  printf '%03d' $((max + 1))
}

slugify() {
  echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]\+/-/g; s/^-//; s/-$//' | cut -c1-40
}

cmd_new() {
  local title="${1:?title required}"
  local id slug file
  id=$(next_id); slug=$(slugify "$title"); file="$OPEN/$id-$slug.md"
  sed -e "s/^id: NNN/id: $id/" \
      -e "s|^title: <one line, imperative>|title: $title|" \
      -e "s/^created: YYYY-MM-DD/created: $(date +%F)/" \
      "$TDIR/_template.md" > "$file"
  echo "$file"
}

cmd_status() {
  local id="${1:?id required}" state="${2:?state required}" file
  case "$state" in
    needs-triage|needs-info|ready|blocked|in-progress|done|wontfix) ;;
    *) echo "Unknown state: $state" >&2; exit 1;;
  esac
  file=$(find_ticket "$id")
  sed -i.bak "s/^status: .*/status: $state/" "$file" && rm -f "$file.bak"
  if [ "$state" = "done" ] || [ "$state" = "wontfix" ]; then
    sed -i.bak "s/^closed:.*/closed: $(date +%F)/" "$file" && rm -f "$file.bak"
    mv "$file" "$DONE/$(basename "$file")"
    echo "$DONE/$(basename "$file")"
  else
    echo "$file"
  fi
}

cmd_close() { cmd_status "$1" done; }

cmd_index() {
  local out="$TDIR/INDEX.md" f id title status prio blocked any=0
  {
    echo "# Ticket index"
    echo
    echo "Generated by \`scripts/ticket.sh index\` on $(date +%F). Do not hand-edit."
    echo
    echo "## Open"
    echo
    echo "| id | status | pri | title | blocked by |"
    echo "|---|---|---|---|---|"
  } > "$out"
  for f in "$OPEN"/*.md; do
    [ -e "$f" ] || continue
    any=1
    id=$(field "$f" id); title=$(field "$f" title)
    status=$(field "$f" status); prio=$(field "$f" priority)
    blocked=$(field "$f" blocked_by)
    echo "| $id | $status | $prio | $title | $blocked |" >> "$out"
  done
  [ "$any" -eq 0 ] && echo "| | | | _no open tickets_ | |" >> "$out"
  {
    echo
    echo "## Closed"
    echo
    echo "| id | title | closed |"
    echo "|---|---|---|"
  } >> "$out"
  for f in "$DONE"/*.md; do
    [ -e "$f" ] || continue
    echo "| $(field "$f" id) | $(field "$f" title) | $(field "$f" closed) |" >> "$out"
  done
  echo "$out"
}

cmd_show() { cat "$(find_ticket "${1:?id required}")"; }

cmd_list() {
  local filter="${1:-}" f
  for f in "$OPEN"/*.md; do
    [ -e "$f" ] || continue
    local s; s=$(field "$f" status)
    [ -n "$filter" ] && [ "$s" != "$filter" ] && continue
    printf '%s  %-13s %-3s %s\n' "$(field "$f" id)" "$s" "$(field "$f" priority)" "$(field "$f" title)"
  done
}

case "${1:-}" in
  new) shift; cmd_new "$@";;
  status) shift; cmd_status "$@";;
  close) shift; cmd_close "$@";;
  index) cmd_index;;
  show) shift; cmd_show "$@";;
  list) shift; cmd_list "${1:-}";;
  *) usage; exit 1;;
esac
